### ISSUE TITLE
can't login to my solid-community-server

### ISSUE THREAD

**Issue by pchampin** [jeff-zucker/solid-shell#14]
I have an instance of solid-community-server running on my server, but I can't login to it using solid-shell.
```
$ solid -l shell
  logging in ...
idp? https://solid.mydomain.com/
username? alice@mydomain.com
password? ****
remote base? https://solid.mydomain.com/alice/
  logged in as <undefined>
>
```
Are the IDP and remote base correct?
On my server log, I see:
```
2022-02-03T18:11:22.235Z [BaseHttpServerFactory] info: Received POST request for /login/password
2022-02-03T18:11:22.295Z [WebAclReader] error: No ACL document found for root container https://solid.champin.net/
```
When I (succesfully) login from another service, I don't see any request to /login/password, is that normal?

NB: I am using solid-community-server and solid-shell from github, both at the latest commit on `main`

**Comment by jeff-zucker** [comment]
The username and password login only works on NSS servers.  To login to CSS you will need to get a JWT using @inrupt/generate-oidc-token.  I will eventually change the opening prompts to prompt for JWT rather than user/pass, but for now the way to set the JWT is described in the solid-shell readme using environment variables.  Feel free to ping me on gitter if you run into problems.

**Comment by pchampin** [comment]
Thanks. I suspected something like that (NB: I'm relatively new to the Solid ecosystem, but the incomatibility between different authn systems has been a recurring painpoint so far).

May I suggest:
- an explicit error message if the login attempt fails (not everyone can inspect the server log at the same time they are attempting to login :wink:)
- this error message might suggest to try the cookie method, with a link to https://github.com/jeff-zucker/solid-node-client (or maybe a solid-shell version of that)

**Comment by pchampin** [comment]
Note also that the warning in the ["Logging in" section of the README](https://github.com/jeff-zucker/solid-shell#logging-in) is not super helpful for newcomers:

> If using an NSS based server such as solidcommunity.net or inrupt.net (...)

The NSS acronym should be unfolded. Even when it's done, the sentence will remain misleading. Consider this: I have installed a Node.js based solid server, so it was not obvious to me at first that it was distinct from the "Node Solid Server". The fact that my server is called "*Community* Solid Server", and that you cite `solidcommunity.net` as an example of NSS instance, comforted me in that confusion!

Don't get me wrong: I understand that things are inevitably messy in an active emerging ecosystem. I don't mean to criticize, but to offer the help of a fresh eye on this :)

**Comment by jeff-zucker** [comment]
Thanks, you are right on both scores - I should explain all abbreviations in the documentation and I should have the text produce warnings.  Since these libraries deal so directly with authn, it has been a three year long struggle to change as the authn protocols for Solid changed.   But I think we are now at a stable point.   I appreciate the feedback, thanks!

**Comment by jeff-zucker** [comment]
Finally documented this stuff -).
