### ISSUE TITLE
error creating folder: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by michielbdejong** [jeff-zucker/solid-shell#4]
```sh
> cf asdf
creating folder 'https://example-user.inrupt.net/asdf'
(node:4973) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'substr' of null
    at /Users/michiel/gh/jeff-zucker/solid-shell/node_modules/solid-file-client/dist/console/index.js:158:27
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:4973) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4973) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by angelo-v** [comment]
I had the same issue and found out that the authentication did not work and this is a aftereffect. See https://forum.solidproject.org/t/trouble-logging-in-via-solid-shell/2529

**Comment by jeff-zucker** [comment]
Sorry, I need to fix the package.json.  It is using an old solid-auth-cli which downstream uses an old trust/jose which needs to be updated to solid/jose.  Once that is updated login should work fine.  For copy-folder you are best off waiting for the new solid-file-client which has a very robust copyFolder.  Due out next week.

**Comment by michielbdejong** [comment]
@jeff-zucker you should speak to @jaxoncreed, he's doing similar work on Solid Auth Client (to be renamed to Solid Authenticator).

**Comment by jeff-zucker** [comment]
@jaxoncreed at some point I'd like to talk with you about [Solid-Rest](https://github.com/jeff-zucker/solid-rest) because it will work best if integrated with the authenticator.   Basically, if the authenticator's fetch() passes non-https URLs to Solid-Rest, it becomes able to handle Solid-Rest storage backends such as the browser's localStorage and eventually Dropbox and other remote storages.  I had talked with Ruben about this but never got around to including it in solid-auth-client.

Also, is your solid-auth-client replacement going to be browser only?

**Comment by jeff-zucker** [comment]
The new version of solid-shell using the new solid-file-client solves this and other issues.
